server:
  port: 8000
#  servlet:
#    context-path: /

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false  #不要向注册中心注册自己
    fetch-registry: false  #禁止检索服务
    #service-url: http://${eureka.instance.hostname}:${server.port}/eureka/
    serviceUrl.defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000

logging:
  path: classpath:logback.xml

spring:
  application:
    name: eureka-server
